### ISSUE TITLE
oml:result missing from ontology

### ISSUE THREAD

**Issue by mbjones** [Semantic-Observations/obs-models#20]
Our alignment diagram references oml:result, but this property is not present in the schema at the namespace URI http://def.seegrid.csiro.au/ontology/om/om-lite . Instead, the property oml:observation_result is listed under the Observation class but is not actually defined in the owl document.  See: http://def.seegrid.csiro.au/ontology/om/om-lite#d4e615

After this is resolved, need to fix it both in the figures and the OWL alignment axioms.

**Comment by dr-shorthair** [comment]
I don't believe this is a bug. 
   http://def.seegrid.csiro.au/ontology/om/om-lite#result 
is in the ontology. 
In the LODE (HTML) view it is listed here 
   http://def.seegrid.csiro.au/ontology/om/om-lite#d4e91 
amongst the Annotation properties. It is classified this way because it is defined as an rdf:Property (and not an owl:ObjectProperty or owl:DatatypeProperty). This classification is deliberate - to allow results of any type, including literals and objects - but puts it strictly outside the OWL model.
